---
title: "Incarceration in the United States"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: https://github.com/annmariebarrett/FinalProject-EDLD2/
    theme: readable
    editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rio)
library(here)
library(janitor)
library(cowplot)
library(colorblindr)
#remotes::install_github("hrbrmstr/albersusa")
library(albersusa)
library(gganimate)
library(transformr)
library(ggthemes)
```

# Earnings

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Final Version

```{r, fig.height=8.5, fig.width=11}
#Import and clean earnings data
earnings <- import(here::here("data", "Earnings_state.xlsx")) %>% 
  characterize() %>% 
  clean_names() %>% 
  na_if('n/a') %>% 
  mutate(non_industry = as.double(non_industry), 
         correctional_industry = as.double(correctional_industry))

#Plot earnings version 3

p1 <- ggplot(earnings, 
             aes(y = state, 
                 x = non_industry)) +
  geom_line(aes(group = state)) +
  geom_point(aes(color = bookend), 
             show.legend = FALSE) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  labs(title = "...and in Non-Industry Jobs", 
       x = "Wage per  hour", 
       y = "") + 
  theme_solarized_2() +
  theme(text = element_text(color = "grey30"), 
        title = element_text(color = "grey30"),
        plot.margin = margin(.5, 1.5, .5, .5, unit = "cm")) +
  scale_x_continuous(limits = c(0, 5.15), labels=scales::label_dollar()) 

p2 <- ggplot(earnings, 
             aes(y = state, 
                 x = correctional_industry)) +
  geom_line(aes(group = state)) +
  geom_point(aes(color = bookend), 
             show.legend = FALSE) +
  scale_color_manual(values = c("#0072B2", "#D55E00")) +
  labs(title = "Earnings in Correctional Industry Jobs", 
       x = "Wage per hour",
       y = "State") +       
       #caption = "Data from Sawyer (2017). https://www.prisonpolicy.org/blog/2017/04/10/wages/") + 
  theme_solarized_2(light = T) +
  theme(text = element_text(color = "grey30"), 
        title = element_text(color = "grey30"), 
        axis.title.y = element_text(size = 16),
        plot.margin = margin(.5, .5, .5, .5, unit = "cm")) +
  scale_x_continuous(labels=scales::label_dollar())
  

#p2 + scale_color_manual(values = c("#D55E00", "#0072B2"))
#p2 + scale_color_manual(values = wes_palette(n = 2, name = "Cavalcanti1"))

plot_grid(p2, p1, rel_widths = c(1, 1.1))

#Strength = It's really effective seeing the two plots next to each other to compare the range of earnings between groups of people. I'm glad you kept the scale the same for both plots. The use of the lines to connect the points is an easy way to pick up on the range. 

#Possible improvements: Combining the plots such that you see the earnings for both groups on one plot. So each state would have 2 rows. I think incorporating the color green could be really nice since your outcome is money #Moolah and coordinating so that colors in the title match the colors used to indicate the group type.  That's interesting that some states did not have any data on the earnings. If you know why that is, and it seems relevant, maybe that could be added in the caption?

  ## CHRIS' COMMENTS:
  ## This plot is great at visualizing differences across states, I love
  ## the two color highs and lows.
  
  ## Suggestions: 
  ## (1) drop the caption on the left plot so there aren't two
  ## (2) If you manually specify `y = ` & `x = `, you can omit the coord_flip(). 
  ## (3) consider making red the "low" color (all preference)
  
 
```

### Version 1

```{r, fig.height=6.5, fig.width=11}
#Plot earnings version 2
p3 <- ggplot(earnings, 
             aes(y = state, 
                 x = non_industry)) +
  geom_line(aes(group = state)) +
  geom_point(aes(color = bookend)) +
  xlim(0, 5.15) +
  labs(title = "Range of Earnings Offered to Incarcerated People in Non-industry Jobs", 
       x = "Wage per  hour", 
       y = "State", 
       caption = "Data from Sawyer (2017). https://www.prisonpolicy.org/blog/2017/04/10/wages/"
       ) 
  #theme_minimal() 
#it might be helpful to have $ signs on the axes. It looks like this limits the range from $0 - $5 to $0 - $2, so that isn't ideal. I tried "label_dollar(1:5))" but that just provided 5 0's.



p4 <- ggplot(earnings, 
             aes(y = state, 
                 x = correctional_industry)) +
  geom_line(aes(group = state)) +
  geom_point(aes(color = bookend)) +
  labs(title = "Range of Earnings Offered to Incarcerated People in Correctional Industry Jobs", 
       x = "Wage per hour", 
       y = "State", 
       caption = "Data from Sawyer (2017). https://www.prisonpolicy.org/blog/2017/04/10/wages/") 
  #theme_minimal() 

plot_grid(p3, p4)
```


# Incarceration Rates

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Rates over Time 

```{r, rig.height = 6, fig.width=8}
incar <- import(here::here("data", "incarceration_rates_by_type.csv")) %>% 
  characterize() %>% 
  clean_names()
  
incar <- incar[-c(93:16383), ]

p5 <- incar %>% 
  pivot_longer(cols = state_prisons:local_jails) %>%
  ggplot(aes(year, value, color = name)) +
  geom_line(size = 1.5) +
  labs(y = "Incarceration Rates", 
       x = "Year", 
       title = "Rates of Incarceration per 100,000 people", 
       caption = "Data compiled by the Prison Policy Initiative. https://www.prisonpolicy.org/data/") + 
  scale_color_OkabeIto(name = "Institution", 
                       labels = c("Federal Prisons", 
                                  "Local Jails", 
                                  "State Prisons")) + 
  theme_solarized_2() +
  theme(text = element_text(color = "grey30"), 
        title = element_text(color = "grey30"),
        plot.margin = margin(.5, .5, .5, .7, unit = "cm"),
        axis.title.y = element_text(margin = margin(0, 15, 0, 0))) +
  transition_reveal(year)

anim_save("rates_linegraph.gif", p5)

#Strengths: Great choice with the color-blind palette. 
#Possible improvements: This feels like a good example of where you can add the label directly onto the plot so they're next to the line graphs. This way you can remove the legend. I think the Week 6 lecture on communication has an example with code. You could probably remove the y-axis label "Year" and incorporate it into the title. Making this plot interactive (with plotly perhaps) might be a nice addition too, and then you can remove some of the vertical lines 

  ## Suggestions: 
  ## (1) you can skip the "group = name" if you have "color = name".
  ## scale_color_OkabeIto() takes the place of scale_color_discrete() 
  ## so I moved your `name =` & `labels =` code 
  ## (2) Also, I just increased the base font size for readability.
```

### Version 1

```{r}
incar %>% 
  pivot_longer(cols = state_prisons:local_jails) %>%
  ggplot(aes(year, value, color = name)) +
  geom_line() +
  labs(y = "Incarceration Rates", 
       x = "Year", 
       title = "Rates of Incarceration per 100,000 people", 
       caption = "Data compiled by the Prison Policy Initiative. https://www.prisonpolicy.org/data/")
  #scale_color_OkabeIto(name = "Institution", 
                      # labels = c("Federal Prisons", 
                                 # "Local Jails", 
                                  #"State Prisons")) + 
 # theme_solarized_2() +
 # theme(text = element_text(color = "grey30"), title = element_text(color = "grey30"))
  #theme_minimal(base_size = 18)
```


# Map of Increasing Rates
Row {.tabset .tabset-fade}
-----------------------  

### Chart C

```{r, include = FALSE, eval = FALSE}
#Import Data
states <- import(here::here("data", "State_rates_time.xlsx")) %>% 
  characterize() %>% 
  clean_names()

#Join map and state prison rate data
us <- usa_sf() %>% 
  mutate(
    state = factor(name))

states_prison <- states %>% 
  filter(institution == "Prison Rate")

states_prison[3:40] <- sapply(states_prison[3:40], as.numeric)

states_prison <- states_prison %>% 
  pivot_longer(cols = starts_with("x"), names_to = "year", values_to = "rates")

states_prison$year <- gsub("[^0-9.-]", "", states_prison$year)

states_prison <- states_prison %>% 
  mutate(year = factor(year))

data_map <- left_join(us, states_prison, by = "state")

#Plot animated map
plot_3 <- 
  ggplot(data_map) +
  geom_sf(aes(fill = rates)) +
  scale_fill_viridis_c(option = "plasma") +
  labs(title = "Rates of Incarceration in State Prisons  in {closest_state}", 
       fill = "Incarceration per 100,000 people",
       caption = "Data from Sawyer (2018). https://www.prisonpolicy.org/reports/women_overtime_table_1.html") +
  theme_solarized_2() +
  theme(legend.position = 'top') +
  transition_states(year,
                    transition_length = 3,
                    state_length = 3) +
  ease_aes('cubic-in-out') +
  enter_fade()

plot_3

animation <- animate(plot_3, 100, fps = 10, duration = 20, 
                     width = 950, height = 750,
                     renderer = gifski_renderer())

anim_save("fig3.gif", animation)

#Possible recommendations: Removing the longitudinal and latitudinal lines might be nice in order to minimize distractions for the viewers. 
#I can't really think of much to change. It could be interesting to see how the rate changes over time using an animated map. (I think you had mentioned wanting to do that.)

  ## CHRIS' COMMENT:
  ## Great plot here, I really like seeing things graphically, and I think 
  ## your use of color palette is nice. Good use of caption in plot. 

  ## Suggestions: 
  ## 1) try the legend at the top (or bottom), it gives the map more space
  ## 2) To echo above: I think an animation would improve this a bit. 
  ## If you pivot into long format, make a column called 'year', and 
  ## change the name of the `fill =` column to reference all years, 
  ## you could animate this with just adding the code below:

##plot_3 + 
  ##transition_states(year) +  
  ##labs(title = 'Rates of Incarceration in State Prisons  in 1978 {next_state}')
```


